using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SuperMemoAssistant.Plugins.MouseoverGlossary
{
  public static class Keywords
  {

    public static Dictionary<string, string> KeywordMap = new Dictionary<string, string>
    {

      { "a-factor",               "https://help.supermemo.org/wiki/Glossary:A-Factor"  },
      { "acquisition rate",       "https://help.supermemo.org/wiki/Glossary:Acquisition_rate"  },
      { "active recall",      "https://help.supermemo.org/wiki/Glossary:Active_recall"  },
      { "auto sort",              "https://help.supermemo.org/wiki/Glossary:Auto-sort"  },
      { "auto-postpone",          "https://help.supermemo.org/wiki/Glossary:Auto-postpone"  },
      { "auto-sort",              "https://help.supermemo.org/wiki/Glossary:Auto-sort"  },
      { "binary component",     "https://help.supermemo.org/wiki/Glossary:Binary_component"  },
      { "branch",              "https://help.supermemo.org/wiki/Glossary:Branch"  },
      { "browser",            "https://help.supermemo.org/wiki/Glossary:Browser"  },
      { "card",             "https://help.supermemo.org/wiki/Glossary:Flashcard"  },
      { "category",             "https://help.supermemo.org/wiki/Glossary:Category"  },
      { "cloze deletion",             "https://help.supermemo.org/wiki/Glossary:Cloze_deletion"  },
      { "cloze item",             "https://help.supermemo.org/wiki/Glossary:Cloze_deletion"  },
      { "cloze question",             "https://help.supermemo.org/wiki/Glossary:Cloze_deletion"  },
      { "cloze",             "https://help.supermemo.org/wiki/Glossary:Cloze_deletion"  },
      { "collection",             "https://help.supermemo.org/wiki/Glossary:Collection"  },
      { "component",          "https://help.supermemo.org/wiki/Glossary:Component"  },
      { "components",          "https://help.supermemo.org/wiki/Glossary:Component"  },
      { "concept group",             "https://help.supermemo.org/wiki/Glossary:Concept_group"  },
      { "concept groups",             "https://help.supermemo.org/wiki/Glossary:Concept_group"  },
      { "concept map",             "https://help.supermemo.org/wiki/Glossary:Concept_map"  },
      { "concept maps",             "https://help.supermemo.org/wiki/Glossary:Concept_map"  },
      { "concept",             "https://help.supermemo.org/wiki/Glossary:Concept"  },
      { "concepts",             "https://help.supermemo.org/wiki/Glossary:Concept"  },
      { "consolidation",             "https://help.supermemo.org/wiki/Glossary:Consolidation"  },
      { "contents window",             "https://help.supermemo.org/wiki/Glossary:Contents_window"  },
      { "delay",             "https://help.supermemo.org/wiki/Glossary:Delay"  },
      { "difficulty",             "https://help.supermemo.org/wiki/Glossary:Difficulty"  },
      { "dismiss",             "https://help.supermemo.org/wiki/Glossary:Dismiss"  },
      { "dismissed",             "https://help.supermemo.org/wiki/Glossary:Dismissed_element"  },
      { "element browser",            "https://help.supermemo.org/wiki/Glossary:Browser"  },
      { "element subset",     "https://help.supermemo.org/wiki/Glossary:Element_subset"  },
      { "element window",             "https://help.supermemo.org/wiki/Glossary:Element_window"  },
      { "element",            "https://help.supermemo.org/wiki/Glossary:Element"  },
      { "elements",            "https://help.supermemo.org/wiki/Glossary:Element"  },
      { "extract",             "https://help.supermemo.org/wiki/Glossary:Extract"  },
      { "extraction",             "https://help.supermemo.org/wiki/Glossary:Extract"  },
      { "extracts",             "https://help.supermemo.org/wiki/Glossary:Extract"  },
      { "fi",             "https://help.supermemo.org/wiki/Glossary:Forgetting_index"  },
      { "final drill",             "https://help.supermemo.org/wiki/Glossary:Final_drill"  },
      { "flash card",             "https://help.supermemo.org/wiki/Glossary:Flashcard"  },
      { "flash cards",             "https://help.supermemo.org/wiki/Glossary:Flashcard"  },
      { "flashcard",             "https://help.supermemo.org/wiki/Glossary:Flashcard"  },
      { "flashcards",             "https://help.supermemo.org/wiki/Glossary:Flashcard"  },
      { "forgetting curve",             "https://help.supermemo.org/wiki/Glossary:Forgetting_curve"  },
      { "forgetting index",             "https://help.supermemo.org/wiki/Glossary:Forgetting_index"  },
      { "free running sleep",             "https://help.supermemo.org/wiki/Glossary:Free_running_sleep"  },
      { "grade",             "https://help.supermemo.org/wiki/Glossary:Grade"  },
      { "grading",             "https://help.supermemo.org/wiki/Glossary:Grade"  },
      { "hook node",             "https://help.supermemo.org/wiki/Glossary:Hook_node"  },
      { "hook",             "https://help.supermemo.org/wiki/Glossary:Hook_node"  },
      { "image occlusion",             "https://help.supermemo.org/wiki/Glossary:Occlusion_test"  },
      { "incremental audio",      "https://help.supermemo.org/wiki/Glossary:Incremental_audio"  },
      { "incremental learning",   "https://help.supermemo.org/wiki/Glossary:Incremental_learning"  },
      { "incremental reading",    "https://help.supermemo.org/wiki/Glossary:Incremental_reading"  },
      { "incremental video",      "https://help.supermemo.org/wiki/Glossary:Incremental_video"  },
      { "incremental writing",    "https://help.supermemo.org/wiki/Glossary:Incremental_writing"  },
      { "interval",           "https://help.supermemo.org/wiki/Glossary:Interval"  },
      { "intervals",           "https://help.supermemo.org/wiki/Glossary:Interval"  },
      { "item",               "https://help.supermemo.org/wiki/Glossary:Item"  },
      { "items",               "https://help.supermemo.org/wiki/Glossary:Item"  },
      { "knowledge tree",     "https://help.supermemo.org/wiki/Glossary:Knowledge_tree"  },
      { "lapse",                  "https://help.supermemo.org/wiki/Glossary:Incremental_reading"  },
      { "leech",             "https://help.supermemo.org/wiki/Glossary:Leech"  },
      { "leeches",             "https://help.supermemo.org/wiki/Glossary:Leech"  },
      { "leitner system",             "https://help.supermemo.org/wiki/Glossary:Leitner"  },
      { "leitner",             "https://help.supermemo.org/wiki/Glossary:Leitner"  },
      { "link",             "https://help.supermemo.org/wiki/Glossary:Link"  },
      { "memory consolidation",             "https://help.supermemo.org/wiki/Glossary:Consolidation"  },
      { "minimum information principle",             "https://help.supermemo.org/wiki/Glossary:Minimum_information_principle"  },
      { "neural creativity",             "https://help.supermemo.org/wiki/Glossary:Neural_creativity"  },
      { "neural queue",             "https://help.supermemo.org/wiki/Glossary:Neural_queue"  },
      { "neural review",             "https://help.supermemo.org/wiki/Glossary:Neural_review"  },
      { "occlusion test",             "https://help.supermemo.org/wiki/Glossary:Occlusion_test"  },
      { "occlusion",             "https://help.supermemo.org/wiki/Glossary:Occlusion_test"  },
      { "optimum interval",             "https://help.supermemo.org/wiki/Glossary:Optimum_interval"  },
      { "ordinal number",             "https://help.supermemo.org/wiki/Glossary:Ordinal_number"  },
      { "outstanding element",             "https://help.supermemo.org/wiki/Glossary:Outstanding_element"  },
      { "outstanding material",             "https://help.supermemo.org/wiki/Glossary:Outstanding_material"  },
      { "outstanding queue",             "https://help.supermemo.org/wiki/Glossary:Outstanding_queue"  },
      { "overload",             "https://help.supermemo.org/wiki/Glossary:Overload"  },
      { "overloaded",             "https://help.supermemo.org/wiki/Glossary:Overload"  },
      { "passive review",             "https://help.supermemo.org/wiki/Glossary:Passive_review"  },
      { "priorities",             "https://help.supermemo.org/wiki/Glossary:Priority"  },
      { "priority bias",             "https://help.supermemo.org/wiki/Glossary:Priority_bias"  },
      { "priority queue",             "https://help.supermemo.org/wiki/Glossary:Priority_queue"  },
      { "priority",             "https://help.supermemo.org/wiki/Glossary:Priority"  },
      { "recognition",             "https://help.supermemo.org/wiki/Glossary:Recognition"  },
      { "registry window",             "https://help.supermemo.org/wiki/Glossary:Registry_window"  },
      { "registry",             "https://help.supermemo.org/wiki/Glossary:Registry"  },
      { "repetition spacing",             "https://help.supermemo.org/wiki/Glossary:Spaced_repetition"  },
      { "repetition",         "https://help.supermemo.org/wiki/Glossary:Repetition"  },
      { "repetitions",         "https://help.supermemo.org/wiki/Glossary:Repetition"  },
      { "requested forgetting index",             "https://help.supermemo.org/wiki/Glossary:Requested_forgetting_index"  },
      { "retention",             "https://help.supermemo.org/wiki/Glossary:Retention"  },
      { "retrievability",             "https://help.supermemo.org/wiki/Glossary:Retrievability"  },
      { "review",             "https://help.supermemo.org/wiki/Glossary:Review"  },
      { "sm",                 "https://help.supermemo.org/wiki/Glossary:SuperMemo"  },
      { "spacing effect",             "https://help.supermemo.org/wiki/Glossary:Spacing_effect"  },
      { "spreading activation",             "https://help.supermemo.org/wiki/Glossary:Spreading_activation"  },
      { "stability",             "https://help.supermemo.org/wiki/Glossary:Stability"  },
      { "startup interval",             "https://help.supermemo.org/wiki/Glossary:Startup_interval"  },
      { "subset browser",     "https://help.supermemo.org/wiki/Glossary:Browser"  },
      { "subset review",             "https://help.supermemo.org/wiki/Glossary:Subset_review"  },
      { "subset",             "https://help.supermemo.org/wiki/Glossary:Subset"  },
      { "super memo",         "https://help.supermemo.org/wiki/Glossary:SuperMemo"  },
      { "super-memo",         "https://help.supermemo.org/wiki/Glossary:SuperMemo"  },
      { "supermemo",          "https://help.supermemo.org/wiki/Glossary:SuperMemo"  },
      { "task",             "https://help.supermemo.org/wiki/Glossary:Task"  },
      { "tasks",             "https://help.supermemo.org/wiki/Glossary:Task"  },
      { "tasklist",             "https://help.supermemo.org/wiki/Glossary:Tasklist"  },
      { "task list",             "https://help.supermemo.org/wiki/Glossary:Tasklist"  },
      { "template",             "https://help.supermemo.org/wiki/Glossary:Template"  },
      { "topic",              "https://help.supermemo.org/wiki/Glossary:Topic"  },
      { "topics",              "https://help.supermemo.org/wiki/Glossary:Topic"  },

    };

  }
}
